name       : python-iso8601
version    : 0.1.16
release    : 2
source     :
    - https://pypi.io/packages/source/i/iso8601/iso8601-0.1.16.tar.gz : 36532f77cc800594e8f16641edae7f1baf7932f05d8e508545b95fc53c6dc85b
homepage   : https://pyiso8601.readthedocs.io/en/latest/
license    : MIT
component  : programming.python
summary    : Simple module to parse ISO 8601 dates
description: |
    Simple module to parse ISO 8601 dates
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
